apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
  labels:
    app: app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: 760486049168.dkr.ecr.eu-west-1.amazonaws.com/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9090
              name: grpc-server
