apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: "api.apptest.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-api-service
                port:
                  number: 80
  tls:
    - hosts:
        - api.apptest.com
      secretName: app-api-cert
