apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-grpc
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: "gapi.apptest.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-api-service
                port:
                  number: 90
  tls:
    - hosts:
        - gapi.apptest.com
      secretName: app-gapi-cert
